const TYPES:{[key:string]:string}={
    FETCH_DATA_CATEGORIES_SUCCESS: 'FETCH_DATA_CATEGORIES_SUCCESS',
    FETCH_DATA_CATEGORIES_LOADING:'FETCH_DATA_CATEGORIES_LOADING',
    FETCH_DATA_CATEGORIES_ERROR: 'FETCH_DATA_CATEGORIES_ERROR',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_LOADING: 'ADD_NEW_CATEGORY_LOADING',
    ADD_NEW_CATEGORY_ERROR: 'ADD_NEW_CATEGORY_ERROR',
    
};
export {TYPES}