const TYPES:{[key:string]:string}={
    FETCH_DATA_CATEGORIES_SUCCESS: 'FETCH_DATA_CATEGORIES_SUCCESS',
    FETCH_DATA_CATEGORIES_LOADING:'FETCH_DATA_CATEGORIES_LOADING',
    FETCH_DATA_CATEGORIES_ERROR: 'FETCH_DATA_CATEGORIES_ERROR',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_LOADING: 'ADD_NEW_CATEGORY_LOADING',
    ADD_NEW_CATEGORY_ERROR: 'ADD_NEW_CATEGORY_ERROR',
    UPDATE_CATEGORY_LOADING:'UPDATE_CATEGORY_LOADING',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_ERROR: 'UPDATE_CATEGORY_ERROR',
    DELETE_CATEGORY_LOADING: 'DELETE_CATEGORY_LOADING',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_ERROR: 'DELETE_CATEGORY_ERROR',
    ADD_NEW_CHILDREN_CATEGORY_LOADING: 'ADD_NEW_CHILDREN_CATEGORY_LOADING',
    ADD_NEW_CHILDREN_CATEGORY_SUCCESS: 'ADD_NEW_CHILDREN_CATEGORY_SUCCESS',
    ADD_NEW_CHILDREN_CATEGORY_ERROR: 'ADD_NEW_CHILDREN_CATEGORY_ERROR'
};
export {TYPES}