const TYPES: { [key: string]: string } = {
  FETCH_DATA_PRODUCTS_SUCCESS: 'FETCH_DATA_PRODUCTS_SUCCESS',
  FETCH_DATA_PRODUCTS_LOADING: 'FETCH_DATA_PRODUCTS_LOADING',
  FETCH_DATA_PRODUCTS_ERROR: 'FETCH_DATA_PRODUCTS_ERROR',
  ADD_NEW_PRODUCT_SUCCESS: 'ADD_NEW_PRODUCT_SUCCESS',
  ADD_NEW_PRODUCT_LOADING:'ADD_NEW_PRODUCT_LOADING',
  ADD_NEW_PRODUCT_ERROR:'ADD_NEW_PRODUCT_ERROR',
  UPDATE_PRODUCT_SUCCESS:'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_LOADING:'UPDATE_PRODUCT_LOADING',
  UPDATE_PRODUCT_ERROR:'UPDATE_PRODUCT_ERROR',
};
export { TYPES };
