const TYPES: { [key: string]: string } = {
  FETCH_DATA_PRODUCTS_SUCCESS: 'FETCH_DATA_PRODUCTS_SUCCESS',
  FETCH_DATA_PRODUCTS_LOADING: 'FETCH_DATA_PRODUCTS_LOADING',
  FETCH_DATA_PRODUCTS_ERROR: 'FETCH_DATA_PRODUCTS_ERROR',
};
export { TYPES };
