const TYPES:{[key:string]:string}={
    FETCH_DATA_STAFF_SUCCESS: 'FETCH_DATA_STAFF_SUCCESS',
    FETCH_DATA_STAFF_LOADING:'FETCH_DATA_STAFF_LOADING',
    FETCH_DATA_STAFF_ERROR: 'FETCH_DATA_STAFF_ERROR',
    ADD_NEW_STAFF_SUCCESS: 'ADD_NEW_STAFF_SUCCESS',
    ADD_NEW_STAFF_LOADING: 'ADD_NEW_STAFF_LOADING',
    ADD_NEW_STAFF_ERROR: 'ADD_NEW_STAFF_ERROR',
    UPDATE_STAFF_LOADING:'UPDATE_STAFF_LOADING',
    UPDATE_STAFF_SUCCESS: 'UPDATE_STAFF_SUCCESS',
    UPDATE_STAFF_ERROR: 'UPDATE_STAFF_ERROR',
    DELETE_STAFF_LOADING: 'DELETE_STAFF_LOADING',
    DELETE_STAFF_SUCCESS: 'DELETE_STAFF_SUCCESS',
    DELETE_STAFF_ERROR: 'DELETE_STAFF_ERROR',
};
export {TYPES}