const TYPES:{[key:string]:string}={
    FETCH_DATA_SHIPPING_METHODS_SUCCESS: 'FETCH_DATA_SHIPPING_METHODS_SUCCESS',
    FETCH_DATA_SHIPPING_METHODS_LOADING:'FETCH_DATA_SHIPPING_METHODS_LOADING',
    FETCH_DATA_SHIPPING_METHODS_ERROR: 'FETCH_DATA_SHIPPING_METHODS_ERROR',
    ADD_NEW_SHIPPING_METHOD_SUCCESS: 'ADD_NEW_SHIPPING_METHOD_SUCCESS',
    ADD_NEW_SHIPPING_METHOD_LOADING: 'ADD_NEW_SHIPPING_METHOD_LOADING',
    ADD_NEW_SHIPPING_METHOD_ERROR: 'ADD_NEW_SHIPPING_METHOD_ERROR',
    UPDATE_SHIPPING_METHOD_LOADING:'UPDATE_SHIPPING_METHOD_LOADING',
    UPDATE_SHIPPING_METHOD_SUCCESS: 'UPDATE_SHIPPING_METHOD_SUCCESS',
    UPDATE_SHIPPING_METHOD_ERROR: 'UPDATE_SHIPPING_METHOD_ERROR',
    DELETE_SHIPPING_METHOD_LOADING: 'DELETE_SHIPPING_METHOD_LOADING',
    DELETE_SHIPPING_METHOD_SUCCESS: 'DELETE_SHIPPING_METHOD_SUCCESS',
    DELETE_SHIPPING_METHOD_ERROR: 'DELETE_SHIPPING_METHOD_ERROR',
};
export {TYPES}