const TYPES: { [key: string]: string } = {
    FETCH_DATA_CUSTOMERS_SUCCESS: 'FETCH_DATA_CUSTOMERS_SUCCESS',
    FETCH_DATA_CUSTOMERS_LOADING: 'FETCH_DATA_CUSTOMERS_LOADING',
    FETCH_DATA_CUSTOMERS_ERROR: 'FETCH_DATA_CUSTOMERS_ERROR',
    ADD_NEW_CUSTOMER_SUCCESS: 'ADD_NEW_CUSTOMER_SUCCESS',
    ADD_NEW_CUSTOMER_LOADING:'ADD_NEW_CUSTOMER_LOADING',
    ADD_NEW_CUSTOMER_ERROR:'ADD_NEW_CUSTOMER_ERROR',
    UPDATE_CUSTOMER_SUCCESS:'UPDATE_CUSTOMER_SUCCESS',
    UPDATE_CUSTOMER_LOADING:'UPDATE_CUSTOMER_LOADING',
    UPDATE_CUSTOMER_ERROR:'UPDATE_CUSTOMER_ERROR',
    FETCH_DETAIL_CUSTOMER_LOADING:'FETCH_DETAIL_CUSTOMER_LOADING',
    FETCH_DETAIL_CUSTOMER_SUCCESS:'FETCH_DETAIL_CUSTOMER_SUCCESS',
    FETCH_DETAIL_CUSTOMER_ERROR:'FETCH_DETAIL_CUSTOMER_ERROR',
    DELETE_CUSTOMER_LOADING: 'DELETE_CUSTOMER_LOADING',
    DELETE_CUSTOMER_SUCCESS:'DELETE_CUSTOMER_SUCCESS',
    DELETE_CUSTOMER_ERROR:'DELETE_CUSTOMER_ERROR'
  };
  export { TYPES };
  