const TYPES: { [key: string]: string } = {
    FETCH_DATA_ORDERS_SUCCESS: 'FETCH_DATA_ORDERS_SUCCESS',
    FETCH_DATA_ORDERS_LOADING: 'FETCH_DATA_ORDERS_LOADING',
    FETCH_DATA_ORDERS_ERROR: 'FETCH_DATA_ORDERS_ERROR',
    ADD_NEW_ORDER_SUCCESS: 'ADD_NEW_ORDER_SUCCESS',
    ADD_NEW_ORDER_LOADING:'ADD_NEW_ORDER_LOADING',
    ADD_NEW_ORDER_ERROR:'ADD_NEW_ORDER_ERROR',
    UPDATE_STATUS_ORDER_SUCCESS:'UPDATE_STATUS_ORDER_SUCCESS',
    UPDATE_STATUS_ORDER_LOADING:'UPDATE_STATUS_ORDER_LOADING',
    UPDATE_STATUS_ORDER_ERROR:'UPDATE_STATUTS_ORDER_ERROR',
    FETCH_DETAIL_ORDER_LOADING:'FETCH_DETAIL_ORDER_LOADING',
    FETCH_DETAIL_ORDER_SUCCESS:'FETCH_DETAIL_ORDER_SUCCESS',
    FETCH_DETAIL_ORDER_ERROR:'FETCH_DETAIL_ORDER_ERROR',
  };
  export { TYPES };
  